const UserActionTypes = {
	GOOGLE_SIGN_IN_START: 'GOOGLE_SIGN_IN_START',
	EMAIL_SIGN_IN_START: 'EMAIL_SIGN_IN_START',
	/**
	 * We don't need individual GOOGLE and EMAIL
	 * SIGN_IN_FAILURE or SIGN_IN_SUCCESS types because
	 * they behave the same
	 */
	SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
	SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',
	CHECK_USER_SESSION: 'CHECK_USER_SESSION',
	SIGN_OUT_START: 'SIGN_OUT_START',
	SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
	SIGN_OUT_FAILURE: 'SIGN_OUT_FAILURE',
};

export default UserActionTypes;
